version: "3.8"
services:
  dlask_db:
    container_name: dlask_db
    image: postgres
    env_file: 
      - ./env/db/dev.env
    volumes:
      - dlask_postgres:/data/postgres
  
  dlask_app:
    build: .
    command: python app.py
    container_name: dlask_app
    ports:
      - "5000:5000"
    env_file: 
      - ./env/app/dev.env
    volumes:
      - ./src:/src
    depends_on:
      - dlask_db

  dlask_db_admin:
    container_name: dlask_db_admin
    image: dpage/pgadmin4
    env_file: 
      - ./env/db/dev.env
    volumes:
      - dlask_pgadmin:/root/.pgadmin
    ports:
      - '5050:80'
    links:
      - 'dlask_db:pgsql-server'

volumes:
  dlask_postgres:
  dlask_pgadmin:

  